Make highlighted inline text bold only
nature-of-code/noc-book-2 pull request #364
Opened 2023-07-28 07:51 UTC by tuantinghuang

Relate #346 

<img width="725" alt="Screenshot 2023-07-28 at 3 45 56 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/1fd412b6-7aa2-4551-8ad5-cf285d2e0112">

2023-07-28 07:51 UTC, tuantinghuang commented
The` <em> `tag by default make texts italic. The root solution might be going into Notion and make all the bold italic font bold only, so that the html wouldn't be consisted of `<strong><em>Text<em><strong>`, but instead `<strong> Text <strong>`. This pull request is changing the styling from the CSS side, instead of Notion.

<img width="821" alt="Screenshot 2023-07-28 at 3 49 10 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/b7288a31-7d3d-424f-b286-066697439e94">

2023-08-01 19:24 UTC, shiffman commented
> The`\<em\>`tag by default make texts italic. The root solution might be going into Notion and make all the bold italic font bold only, so that the html wouldn't be consisted of `\<strong\>\<em\>Text\<em\>\<strong\>`, but instead `\<strong\> Text \<strong\>`. This pull request is changing the styling from the CSS side, instead of Notion.
> 
> <img alt="Screenshot 2023-07-28 at 3 49 10 PM" width="821" src="https://user-images.githubusercontent.com/90000947/256758984-b7288a31-7d3d-424f-b286-066697439e94.png">

Ah, yes, I think we should just fix the text in Notion as there's no reason to remove the possibility of having bold+italic text if we want it in the future. If you agree @tuantinghuang we can close this pull request and make the fixes in Notion itself.

2023-08-02 13:44 UTC, shiffman commented
Noting also from #351 that some of the bold text has a "font-weight" (is this the right CSS property?) that is too high. Let's look at all "bold" text in the PDF and try to make it consistent?

![Screen Shot 2023-08-02 at 7 55 25 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/35279731-606f-4d1b-a9eb-d39ae13f9a49)

2023-08-04 06:19 UTC, tuantinghuang commented
I went through all 10 chapters in Notion and changed most bold italic text to just bold. There are a couple of exceptions - 
- Some number/bullet lists are left as is. I saw three versions (bold, italic, bold italic) throughout the book. We might need to decide on one styling!

- The bold italic comments in code blocks are left as is, as I'm unsure what kind of treatment they should have. 
<img width="802" alt="Screenshot 2023-08-04 at 2 15 03 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/3e836e0e-02e2-4481-a5f0-c3628b3b30a7">

2023-08-04 06:39 UTC, tuantinghuang reviewed
After adjusting in Notion and removing the styling for `<em>` tag, the double bolded issue as mentioned in the earlier comment is also solved!

This is before & after:
Before
<img width="645" alt="Screenshot 2023-08-04 at 2 33 06 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/c02d8505-6158-4534-b6cd-34bbce3bcefa">

After
<img width="634" alt="Screenshot 2023-08-04 at 2 33 37 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/a1bf3ba2-704a-49cb-a4e8-1b0581501d57">

and fixed Chapter 2 -
<img width="1054" alt="Screenshot 2023-08-04 at 2 34 12 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/07734ef6-d901-4bfb-b89e-edb75fe4c68b">

2023-08-04 07:25 UTC, jasongao97 requested changes
Looking great! One tiny thing, could you please add a space between the selector and the `{`. It's a [common standard](https://google.github.io/styleguide/htmlcssguide.html#Declaration_Block_Separation) and also what we use in this project.

2023-08-04 13:52 UTC, shiffman commented on magicbook/stylesheets/components/typography.scss
> +strong{
```suggestion
strong {
```

2023-08-04 13:53 UTC, shiffman commented
@jasongao97 I added the space, if it looks good to you, please merge!

2023-08-04 13:53 UTC, shiffman commented
And thank you @tuantinghuang!

2023-08-04 13:54 UTC, jasongao97 commented
Thank you so much!

2023-08-04 13:54 UTC, merged